server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jcastillo20/Microservicios.git
          searchPaths: Config-Data
          username: jcastillo20
          password: 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

  security:
    user:
      name: root
      password: s3cr3t